project:
  type: website
  output-dir: docs

website:
  title: "Future Doctor of COLORADO"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - Hobbies.qmd

format:
  html:
    theme: vapor
    linkcolor: "#0000FF"



